row1:
  gatekeeper:
  sip:
  security_filevault_status:
row2:
  firmwarepw:
  findmymac:
  firewall_state:
row3:
  skel_state:
  ssh_state:
  root_user:
row4:
  t2_secureboot:
  t2_externalboot:
  activation_lock:
row5:
  as_security_mode:
  user_mdm_control:
  dep_mdm_control:
row6:
  third_party_kexts:
  screen_locked:
